version: '3'

volumes:
  dchat_production_postgres_data: {}
  dchat_production_postgres_data_backups: {}
  dchat_production_file_storage: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: dchat_production_django
    container_name: dchat_production_django

    depends_on:
      - postgres
      - redis
      - mailpit

    volumes:
      - dchat_production_file_storage:/storage

    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  redis:
    image: redis:6
    container_name: dchat_production_redis

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: dchat_production_postgres
    container_name: dchat_production_postgres
    volumes:
      - dchat_production_postgres_data:/var/lib/postgresql/data
      - dchat_production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  mailpit:
    image: axllent/mailpit:latest
    container_name: dchat_local_mailpit
    ports:
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  celeryworker:
    <<: *django
    image: dchat_production_celeryworker
    container_name: dchat_production_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  mediaserver:
    build:
      context: .
      dockerfile: ./compose/production/media_server/Dockerfile
    image: dchat_production_mediaserver
    container_name: dchat_production_mediaserver
    depends_on:
      - django

    volumes:
      - dchat_production_file_storage:/user/share/nginx/storage:ro

  httpserver:
    build:
      context: .
      dockerfile: ./compose/production/http_server/Dockerfile
    image: dchat_production_http_server
    container_name: dchat_production_http_server
    depends_on:
      - django

    ports:
      - "80:80"
