# Generated by Django 5.0.1 on 2024-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dchat_messages', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('BLOCKED', 'Blocked'), ('REJECTED', 'Rejected')], max_length=30),
        ),
    ]
