#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py makemigrations
python manage.py migrate
python /app/manage.py collectstatic --noinput
exec uvicorn dchat.asgi:application --host 0.0.0.0
